import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ReactQueryProvider from "@/modules/common/ReactQueryProvider";
import HomeLayout from "@/modules/home/layouts/HomeLayout";
import { Toaster } from "sonner";
import UserInitializer from "@/modules/auth/common/UserInitializer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body className={inter.className}>
          <ReactQueryProvider>
            <HomeLayout>
              <UserInitializer />
              {children}
              <Toaster position="bottom-center" richColors />
            </HomeLayout>
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
